[Mechanism]
name = "./gri30.yaml"

[Initialization]
restart = true
name = "restart.csv"
p_stoich = 0.6

[Numerics]
n_particles = 100
# n_steps = 10
t_stop = 1.0e-2
# dt = 1.0e-6
# dt_sub = 1.0e-7
convergence_metric = "MEAN"
stats_window = 2
rtol = 1.0e-4
min_steps_converge = 100

[Models]
mixing_model = "IEM"

[Conditions]
pressure = 101325.0
comp_fuel = "CH4:1.0"
comp_ox = "O2:0.21,N2:0.79"
T_fuel = 500.0
T_ox = 1800.0
T_init = 1800.0
phi_global = 1.0
tau_res_mode = "DISTRIBUTION"
# tau_res = 1.0e-3
tau_res = "hist_test.csv"
tau_mix = 1.0e-4

[Output]
check_interval = 10
check_variable_names = ["h", "Y_C2H4", "Y_O2", "Y_N2", "Y_CO", "Y_OH", "Y_CO2", "Y_H2O", "age", "tau_res", "T", "Z"]
check_verbose = false
write_raw_interval = 10
write_stats_interval = 10
