[Mechanism]
name = "./gri30.yaml"

[Numerics]
n_particles = 10
n_steps = 10
t_stop = 1.0
dt = 1.0e-8

[Models]
mixing_model = "IEM"

[Conditions]
pressure = 101325.0
comp_fuel = "CH4:1.0"
comp_ox = "O2:0.21,N2:0.79"
T_fuel = 300.0
T_ox = 1200.0
phi_global = 1.0
tau_res = 1.0e-3
tau_mix = 1.0e-4

[Computation]
n_threads = 10